version: "2"

services:
  nginx:
    image: nginx:1.13.12
    container_name: nginx-laravelcrud
    restart: always
    volumes:
      - ./config/docker/nginx_conf:/etc/nginx/conf.d
      - ./:/var/www/html
      -  /usr/bin/ssh:/usr/bin/ssh
    networks:
      laravelcrud_network:
        ipv4_address: 10.11.0.11

  php:
    build:
      context: .
    container_name: php-laravelcrud
    restart: always
    environment:
     - XDEBUG_CONFIG=remote_host=172.17.0.1
     - PHP_IDE_CONFIG=serverName=Local
    volumes:
      - ./:/var/www/html
      -  /usr/bin/ssh:/usr/bin/ssh
      - ./config/docker/volumes/logsxdebug/:/tmp/xdebug_log #Logs for Xdebug
    networks:
      laravelcrud_network:
        ipv4_address: 10.11.0.12

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=123456A
     - MYSQL_DATABASE=laravel_graphql
     - MYSQL_USER=laravel
     - MYSQL_PASSWORD=123456A
    volumes:
     - ./config/docker/volumes/mysql57:/var/lib/mysql
    networks:
      laravelcrud_network:
        ipv4_address: 10.11.0.13

  redis:
    image: redis:3.2.11
    container_name: redis
    restart: always
    networks:
      laravelcrud_network:
        ipv4_address: 10.11.0.14

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      laravelcrud_network:
        ipv4_address: 10.11.0.15

networks:
  laravelcrud_network:
    driver: bridge
    ipam:
      config:
      - subnet: 10.11.0.0/24
        gateway: 10.11.0.1
